### ISSUE TITLE
Option to move the related membership contributions

### ISSUE THREAD

**Issue by masetto** [lcdservices/biz.lcdservices.movemembership#5]
@lcdservices Few months ago I made [this PR](https://github.com/lcdservices/biz.lcdservices.movemembership/pull/2) and it was not merged.

Now I close it because many code is already fixed, but in my opinion the option for move the related membership contributions is useful.

I you think so, I could do another PR for only this feature.

**Comment by lcdservices** [comment]
if you want to update the PR I'll review. I agree it would be useful.

**Comment by masetto** [comment]
See https://github.com/lcdservices/biz.lcdservices.movemembership/pull/6
